### ISSUE TITLE
Stand alone version

### ISSUE THREAD

**Issue by Knowen** [egomeh/anno1800-scripting-api#6]
Hello, is it possible to release an .exe version of this? I really want to use this, but I don't know how to get it to run. 

Thanks in advance

**Comment by egomeh** [comment]
Hi,

Thank you for your message! You are right that the project is in a rather hard-to-use state at the moment.

I've just started work on making the whole thing over. The current version is very hasty as I was uncertain about many things and had to hurry in order to keep up with game updates :P

I'm hoping to leverage the things I've learned to make the next version more friendly from both user and developer perspective.

Feel free to ask more if you want :)

**Comment by egomeh** [comment]
Alright, the mega re-write is good underway. I'm making a priority of having a standalone at some point. I'm closing this issue.
