### ISSUE TITLE
The program gets stuck at acceptedSocket.Wait(); (Telegraph.gen.cs#L63) and blockages related to the game update

### ISSUE THREAD

**Issue by alescis-wuin** [egomeh/anno1800-scripting-api#7]
Hello,

## **The program gets stuck at acceptedSocket.Wait(); (Telegraph.gen.cs#L63)**

_I tested your API by running the TestMonocle source code, but it doesn't work._
The program gets stuck at acceptedSocket.Wait(); https://github.com/egomeh/anno1800-scripting-api/blob/e3e5ab90a63dcb8abac8d51b8c37deab519e31c1/Monocle/Telegraph.gen.cs#L63

## **Problem with local IP address**

I also got something that looks strange to me, the address returned by IPAddress "ipAddress = ipHostInfo.AddressList[0];" https://github.com/egomeh/anno1800-scripting-api/blob/e3e5ab90a63dcb8abac8d51b8c37deab519e31c1/Monocle/Telegraph.gen.cs#L30 is ":::1", if I replace the line with "ipAddress = ipHostInfo. AddressList[1]", I get my local ip address as "000.0.0.0"

Thanks in advance,
Have a good day

**Comment by alescis-wuin** [comment]
Hello,

I have news, the program no longer blocks at "acceptedSocket.Wait();" https://github.com/egomeh/anno1800-scripting-api/blob/e3e5ab90a63dcb8abac8d51b8c37deab519e31c1/Monocle/Telegraph.gen.cs#L63
Randomly, I didn't make any changes except changing the ip from 0 to 1, but it didn't work yesterday with this change.

However, it gets stuck on telegraph.GetAllAreas(out areas); https://github.com/egomeh/anno1800-scripting-api/blob/e3e5ab90a63dcb8abac8d51b8c37deab519e31c1/TestMonocle/Program.cs#L10 As if he was getting no response.

Thanks in advance,
Have a nice day.

**Comment by egomeh** [comment]
Thank you for opening this issue :)

I think there are a few things at play here that I'll try to address.

The first issue, I don't know. I have not seen that myself but I can think of a few gotchas in the setup that might cause some unexpected halts. I'll try to fix those as well.

The problem of being stuck on GetAllAreas is simply because the game was updated two days ago and I have not yet had the time to patch up the code.

When I've addressed both issues, I'll let you know. The latter should be a matter of a few days.

**Comment by alescis-wuin** [comment]
Hello,

Thank you for your responsive response.

I am really sorry about this long text, As we say in French : "Oh ! Pavé César !"

## **Unscheduled stops**

What's surprising is that the stops (before "GetAllAreas") **don't happen anymore**, _I don't know if it's a matter of probability or if there's a reason behind it_. _However, before modifying the local IP, I made other modifications and tests which may have also caused deadlocks again at this level_, **once a new project was set up and only the IP was corrected, this seemed to work, the reason is surely there**.


## **Local IP problem**

To solve the IP problem, can I suggest you to use a code that **analyzes all available local IPs** (in the table) and matches them with a **regex to take the first one that seems correct** 
"from a point of view" syntactic ? (_:::1 -> incorrect, 000.0.0.0 -> correct_), if you wish, I volunteer to help you with this and to do this.


## **Blocking at GetAllAreas**

_It seemed to me that the update could be the cause of the blocking at GetAllAreas._

On this subject, I would like to know, if possible, how do you do to determine the functions of the game so efficiently (through the assembly code I imagine?) as well as the memory addresses.
For example, a line in assembler can easily make one think of a "return" in programming, which signifies the end of a function, but how to find the beginning of a function?
How do you determine which variables come into play, what exactly does this function do, etc?
I also noticed that the memory addresses of the game variables change regularly, especially after restarting it, does this not do the same thing with certain functions?


## **Collaboration**

Finally, **I would like to know if you would allow me to provide you with my assistance, to help you with about this update of the game and find a new solutions ?** _If so, do not hesitate to ask me anything_ and especially **if you would agree to let me join your team in order to help you develop your project**.
I'm not an expert but I have very varied knowledge that can always be useful (memory, pointers, functions, C#, assembly, c/c++, python, java, ...)

Thanks in advance,
Have a good day.

**Comment by egomeh** [comment]
Hi again,

Don't worry about text size :)

## Unscheduled stops

I have to admit, the code is probably a little hostile to newcomers. I've not documented it too well and as mentioned, there are a bunch of nasty pitfalls. It could very well be that you fell in :) The whole IP/socket thing has taken little of my focus so there is probably a bunch of things to improve.

## Local IP problem

As with the above, I'm not too certain about it. If you want to give it a shot and you can find some way to make it better feel free to make a PR.

## Blocking at GetAllAreas

I cannot give a comprehensive answer, there is too much to unpack. Let me try to give you an overview.

> how do you do to determine the functions

You're right, memory and assembly code. It's more or less what you'd imagine. the process usually goes something like this

  * Have a desire to get information/call function
  * Make assumptions about how it works
  * Try to verify assumptions by either
    * inspect memory
    * inspect code
    * some other ad hoc trick
    * all of the above simultaneously
 
> a line in assembler can easily make one think of a "return"

Yes. If you see `ret` you can be pretty sure that is either the end of a function or at least a point at which it exits.

There are patterns you can find for other sequences in a program. You can look for the `function prologue` and other common function sequences. There are also other patterns you can start to recognize. Two examples could be

#### hashing functions

If you see a bunch of xors, bit shifts, and multiplications, you can make a fair assumption that the function does some hashing.

#### TLS

If you try to compile some code in C++ on Windows and have the code access some TLS data, you might typically see an in instruction like `mov ..., qword ptr gs:[0x58]`


The more you look, the more you start recognizing :)

> How do you determine which variables

This is very labor-intensive to determine for sure. I'd go to great lengths to avoid figuring out exactly what a function does or exactly what structs are in memory. I think it's fair to say that the trick is to draw conclusions on JUST ENOUGH evidence.

If you make an assumption, write some code on that assumption, and the program does not crash, most often you're on the right track. Keep in mind that when you mess with binary code like this, most small mistakes cause a crash right away.

> I also noticed that the memory addresses of the game variables change

Yes and no :)

Code is relative to module location. You can query module location. If you know the code offset from the module, you can always find the code. So the code is the easy part.

The game data is much more difficult. There are many ways to find it. My approach is to find cod that accesses certain data. Then I hook the code and leverage the fact that I can just get read data from registers in the running code.

##  Collaboration

I'd be glad for you to help out. There is no team as such. Over time I've gotten help from various sources. You can contribute pretty much any way you want.

If you want to just read the code and find improvements, just write some code and make a PR :)

If you want to know some more details, since I don't have good documentation so far, I should probably give you some kind of introduction.

**Comment by alescis-wuin** [comment]
Hello again,

Thank you for your reactive and exhaustive answer which allowed me to see much more clearly.

## **Unscheduled stops**

_It's true that the code may seem a bit "hard"' at first but you understand very quickly especially when you are used to reading code. What slowed me down a bit is that my areas of expertise are mainly concentrated around Java and C/C++, although I have a rudimentary knowledge of C# (finally, a lot of languages ​​are alike, it's not so difficult to understand new ones), I don't know the specific ways of doing things, libraries, conventions etc, but with a little time, reading and Console.WriteLine(... ) can be understood very quickly._
However, I don't think I fell into a "trap", I just had modified the IP and it seemed to work after recreating a clean project with this modification.

## **Blocking at GetAllAreas**

_No problem, take your time to understand where the problem comes from, thank you for your work._

## **How ​​do you do to determine the functions**

Thank you for all your answers which enlightens me a lot. It's true that I hadn't thought of it, but between one return and another, there is most likely a function hiding underneath.

## **Collaboration**

I will start by doing the IP analysis code, see how to do it best, I will offer you an overview once finished.
Next, I'll attempt to document the code against the ways I understood it, so you can save some time on this.
I could also write a wiki later if you agree.
I will also let you know if I manage to find functions or some sort of redundancy in the game's memory (I have already started to find something in relation to the various global variables such as money, influence, etc.)
I have some other ideas to slightly improve the code (some small features to help develop or help the user), I'll let you know as soon as I'm done.

If you ever want to discuss somewhere other than on github or by email, don't hesitate to ask me (typically Discord...)

Have a good day !

**Comment by egomeh** [comment]
Alright, hook locations are updated.

There are more issues that need to be addressed but the sample code should work.
